name: Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "pip install -r requirements_dev.txt"
        docs-folder: "docs/"

    - uses: actions/upload-artifact@v1
      with:
        name: Documentation
        path: docs/_build/html/

    - name: Commit Docs to GH Pages
      run: |
        git clone https://github.com/ramiawar/fastabm.git --branch gh-pages --single-branch gh-pages
        cp -r docs/_build/html/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "rami.awar.ra@gmail.com"
        git config --local user.name "Rami Awar"
        git add .
        git commit -m "Update documentation" -a || true

    - name: Push docs
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}